CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'default'@'%' IDENTIFIED BY 'default';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'default'@'%' WITH GRANT OPTION;
ALTER USER 'root'@'%' IDENTIFIED BY '';
ALTER USER 'default'@'%' IDENTIFIED BY 'default';
FLUSH PRIVILEGES;
