"""4.0.0 migrations

Revision ID: bdbc4797881b
Revises: 70acfb3fc8d6
Create Date: 2024-11-16 15:23:37.451641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbc4797881b'
down_revision: Union[str, None] = '70acfb3fc8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('app', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'app')
    # ### end Alembic commands ###
