"""add_download_time

Revision ID: a843b8b3d35c
Revises: bc1775d0fc21
Create Date: 2025-02-06 21:31:26.532441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a843b8b3d35c'
down_revision: Union[str, None] = 'bc1775d0fc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloaded', sa.Column('download_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('requests', sa.Column('download_time', sa.TIMESTAMP(), nullable=True))
    op.drop_column('requests', 'downloaded_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('downloaded_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('requests', 'download_time')
    op.drop_column('downloaded', 'download_time')
    # ### end Alembic commands ###
